### ISSUE TITLE
Interval

### ISSUE THREAD

**Issue by lupoxanesp8266** [sstaub/Ticker#1]
Could you set the timing interval in microseconds? I mean: 
            flipper.attach_ms(0.25, flip);

**Comment by sstaub** [comment]
It is now possible. You can change the interval format to us instead of ms, by using MICROS_MICROS
for the resolution.
`Ticker flipper(counter_us, 250, 0, MICROS_MICROS); // calls the function counter_us every 250us`
On normal Arduino's like UNO it is is not very exactly when using intervals under 1ms but on ESP?
you have to test it or you should use the hardware timers with an ISR for really high resolution.
