### ISSUE TITLE
can i start a func which have a argument?

### ISSUE THREAD

**Issue by morestart** [sstaub/Ticker#6]
RT

**Comment by sstaub** [comment]
Did you try it?  I think it is not possible because of the function pointer type, but try it.

**Comment by morestart** [comment]
> Did you try it? I think it is not possible because of the function pointer type, but try it.

Thanks for your replay, i will try it. If it is not possible, i thinks i can use global variable and  i will close this issue.

**Comment by pedzed** [comment]
The reason for my project not using this is for this primary reason. Otherwise, it looks like a nice library.

I also tried to use an anonymous function (lambda), but that didn't work as it does not seem to be supported by this library.

I opted for https://github.com/avandalen/VirtualDelay instead.

**Comment by morestart** [comment]
> The reason for my project not using this library is for this primary reason. Otherwise, it looks like a nice library.
> 
> I also tried to use an anonymous function (lambda), but that didn't work as it does not seem to be supported by this library.
> 
> I opted for https://github.com/avandalen/VirtualDelay instead.

But it only support UNO, i what to find a ticker that can support esp8266 or esp32
